/// A DX cluster spot for client-side display.
#[derive(Clone, Debug)]
pub struct DxSpotInfo {
    pub callsign: String,
    pub frequency_hz: u64,
    pub mode: String,
    pub spotter: String,
    pub comment: String,
    pub age_seconds: u16,
    /// Total spot lifetime in seconds (from server config)
    pub expiry_seconds: u16,
    /// When this spot was last received (for client-side expiry)
    pub received: std::time::Instant,
}

/// RGBA color for a DX spot mode string.
pub fn mode_color_rgba(mode: &str, alpha: u8) -> [u8; 4] {
    match mode {
        "CW" => [255, 255, 0, alpha],       // yellow
        "SSB" => [0, 255, 0, alpha],        // green
        "FT8" | "FT4" | "DIGI" => [0, 255, 255, alpha], // cyan
        _ => [255, 255, 255, alpha],        // white
    }
}

/// Read-only radio state, broadcast from engine to UI via tokio::sync::watch.
#[derive(Clone, Debug)]
pub struct RadioState {
    // Connection
    pub connected: bool,
    pub ptt_denied: bool,
    pub audio_error: bool,

    // Stats
    pub rtt_ms: u16,
    pub jitter_ms: f32,
    pub buffer_depth: u32,
    pub rx_packets: u64,
    pub loss_percent: u8,

    // Audio levels
    pub capture_level: f32,
    pub playback_level: f32,
    pub playback_level_bin_r: f32,
    pub playback_level_rx2: f32,
    pub playback_level_yaesu: f32,
    pub yaesu_mic_level: f32,

    // Radio
    pub frequency_hz: u64,
    pub mode: u8,
    pub smeter: u16,

    // Thetis controls
    pub power_on: bool,
    pub tx_profile: u8,
    pub nr_level: u8,
    pub anf_on: bool,
    pub drive_level: u8,
    pub rx_af_gain: u8,
    pub agc_enabled: bool,
    pub other_tx: bool,
    pub recording: bool,
    pub playing: bool,
    pub last_recorded_path: Option<String>,
    pub thetis_swr_x100: u16,
    pub filter_low_hz: i32,
    pub filter_high_hz: i32,
    pub thetis_starting: bool,
    pub mon_on: bool,
    pub tx_profile_names: Vec<String>,

    // RX2 / VFO-B
    pub rx2_enabled: bool,
    pub vfo_sync: bool,
    pub frequency_rx2_hz: u64,
    pub mode_rx2: u8,
    pub smeter_rx2: u16,
    pub rx2_af_gain: u8,
    pub rx2_nr_level: u8,
    pub rx2_anf_on: bool,
    pub rx2_agc_mode: u8,
    pub rx2_agc_gain: u8,
    pub rx2_sql_enable: bool,
    pub rx2_sql_level: u8,
    pub rx2_nb_enable: bool,
    pub rx2_binaural: bool,
    pub rx2_apf_enable: bool,
    pub rx2_vfo_lock: bool,
    pub filter_rx2_low_hz: i32,
    pub filter_rx2_high_hz: i32,

    // RX2 Spectrum
    pub rx2_spectrum_bins: Vec<u16>,
    pub rx2_spectrum_center_hz: u32,
    pub rx2_spectrum_span_hz: u32,
    pub rx2_spectrum_ref_level: i8,
    pub rx2_spectrum_db_per_unit: u8,
    pub rx2_spectrum_sequence: u16,
    pub rx2_full_spectrum_bins: Vec<u16>,
    pub rx2_full_spectrum_center_hz: u32,
    pub rx2_full_spectrum_span_hz: u32,
    pub rx2_full_spectrum_sequence: u16,

    // Spectrum (extracted view for spectrum line)
    pub spectrum_bins: Vec<u16>,
    pub spectrum_center_hz: u32,
    pub spectrum_span_hz: u32,
    pub spectrum_ref_level: i8,
    pub spectrum_db_per_unit: u8,
    pub spectrum_sequence: u16,

    // Full DDC spectrum (for waterfall history — covers entire DDC bandwidth)
    pub full_spectrum_bins: Vec<u16>,
    pub full_spectrum_center_hz: u32,
    pub full_spectrum_span_hz: u32,
    pub full_spectrum_sequence: u16,

    // External equipment: Amplitec 6/2 antenna switch
    pub amplitec_connected: bool,
    pub amplitec_switch_a: u8,  // 0=unknown, 1-6
    pub amplitec_switch_b: u8,
    pub amplitec_labels: String,  // comma-separated: "a1,a2,...,a6,b1,...,b6" (empty = not received)

    // JC-4s antenna tuner
    pub tuner_connected: bool,  // Hardware connected
    pub tuner_state: u8,        // 0=Idle, 1=Tuning, 2=DoneOk, 3=Timeout, 4=Aborted
    pub tuner_can_tune: bool,   // Amplitec switch A on JC-4s position

    // SPE Expert 1.3K-FA power amplifier
    pub spe_connected: bool,
    pub spe_state: u8,        // 0=Off, 1=Standby, 2=Operate
    pub spe_band: u8,         // band code
    pub spe_ptt: bool,
    pub spe_power_w: u16,
    pub spe_swr_x10: u16,
    pub spe_temp: u8,
    pub spe_warning: u8,
    pub spe_alarm: u8,
    pub spe_power_level: u8,  // 0=L, 1=M, 2=H
    pub spe_antenna: u8,
    pub spe_input: u8,
    pub spe_voltage_x10: u16,
    pub spe_current_x10: u16,
    pub spe_atu_bypassed: bool,
    pub spe_available: bool,    // true once any SPE status packet received
    pub spe_active: bool,       // true if SPE is the active PA for drive control

    // RF2K-S power amplifier
    pub rf2k_connected: bool,
    pub rf2k_operate: bool,
    pub rf2k_band: u8,
    pub rf2k_frequency_khz: u16,
    pub rf2k_temperature_x10: u16,
    pub rf2k_voltage_x10: u16,
    pub rf2k_current_x10: u16,
    pub rf2k_forward_w: u16,
    pub rf2k_reflected_w: u16,
    pub rf2k_swr_x100: u16,
    pub rf2k_max_forward_w: u16,
    pub rf2k_max_reflected_w: u16,
    pub rf2k_max_swr_x100: u16,
    pub rf2k_error_state: u8,
    pub rf2k_error_text: String,
    pub rf2k_antenna_type: u8,
    pub rf2k_antenna_number: u8,
    pub rf2k_tuner_mode: u8,
    pub rf2k_tuner_setup: String,
    pub rf2k_tuner_l_nh: u16,
    pub rf2k_tuner_c_pf: u16,
    pub rf2k_tuner_freq_khz: u16,
    pub rf2k_segment_size_khz: u16,
    pub rf2k_drive_w: u16,
    pub rf2k_modulation: String,
    pub rf2k_max_power_w: u16,
    pub rf2k_device_name: String,
    pub rf2k_available: bool,
    pub rf2k_active: bool,      // true if RF2K is the active PA for drive control
    // RF2K-S debug (Fase D)
    pub rf2k_debug_available: bool,
    pub rf2k_bias_pct_x10: u16,
    pub rf2k_psu_source: u8,
    pub rf2k_uptime_s: u32,
    pub rf2k_tx_time_s: u32,
    pub rf2k_error_count: u16,
    pub rf2k_error_history: Vec<(String, String)>,
    pub rf2k_storage_bank: u16,
    pub rf2k_hw_revision: String,
    pub rf2k_frq_delay: u16,
    pub rf2k_autotune_threshold_x10: u16,
    pub rf2k_dac_alc: u16,
    pub rf2k_high_power: bool,
    pub rf2k_tuner_6m: bool,
    pub rf2k_band_gap_allowed: bool,
    pub rf2k_controller_version: u16,
    pub rf2k_drive_config_ssb: [u8; 11],
    pub rf2k_drive_config_am: [u8; 11],
    pub rf2k_drive_config_cont: [u8; 11],

    // UltraBeam RCU-06
    pub ub_connected: bool,
    pub ub_frequency_khz: u16,
    pub ub_band: u8,
    pub ub_direction: u8,
    pub ub_off_state: bool,
    pub ub_motors_moving: u8,
    pub ub_motor_completion: u16,
    pub ub_fw_major: u8,
    pub ub_fw_minor: u8,
    pub ub_available: bool,
    pub ub_elements_mm: [u16; 6],
    // DX Cluster spots
    pub dx_spots: Vec<DxSpotInfo>,

    // EA7HG Visual Rotor
    pub rotor_connected: bool,
    pub rotor_angle_x10: u16,
    pub rotor_rotating: bool,
    pub rotor_target_x10: u16,
    pub rotor_available: bool,

    // Yaesu FT-991A
    pub yaesu_connected: bool,
    pub yaesu_freq_a: u64,
    pub yaesu_freq_b: u64,
    pub yaesu_mode: u8,
    pub yaesu_smeter: u16,
    pub yaesu_tx_active: bool,
    pub yaesu_power_on: bool,
    pub yaesu_af_gain: u8,
    pub yaesu_tx_power: u8,
    pub yaesu_squelch: u8,
    pub yaesu_rf_gain: u8,
    pub yaesu_mic_gain: u8,
    pub yaesu_split: bool,
    pub yaesu_scan: bool,
    pub yaesu_vfo_select: u8,  // 0=VFO, 1=Memory, 2=MemTune
    pub yaesu_memory_channel: u16,
    pub yaesu_memory_data: Option<String>,
    // New TCI controls (v2.10.3.13)
    pub agc_mode: u8,       // 0=off, 1=long, 2=slow, 3=med, 4=fast, 5=custom
    pub agc_gain: u8,       // 0-120
    pub rit_enable: bool,
    pub rit_offset: i16,    // Hz
    pub xit_enable: bool,
    pub xit_offset: i16,    // Hz
    pub sql_enable: bool,
    pub sql_level: u8,      // 0-160
    pub nb_enable: bool,
    pub nb_level: u8,  // 0=off, 1=NB1, 2=NB2
    pub agc_auto_rx1: bool,
    pub agc_auto_rx2: bool,
    pub cw_keyer_speed: u8, // WPM
    pub vfo_lock: bool,
    pub binaural: bool,
    pub apf_enable: bool,
    pub mute: bool,
    pub rx_mute: bool,
    pub nf_enable: bool,
    pub rx2_nf_enable: bool,
    pub rx_balance: i8,
    pub tune_drive: u8,     // 0-100
    pub mon_volume: i8,     // dB, typically -40..0

    pub auth_rejected: bool,
    pub totp_required: bool,
    pub diversity_enabled: bool,
    pub diversity_ref: u8,
    pub diversity_source: u8,
    pub diversity_gain_rx1: u16,
    pub diversity_gain_rx2: u16,
    pub diversity_phase: u16, // encoded: phase*100 + 18000

    pub ddc_sample_rate_rx1: u16, // kHz (e.g. 192, 384, 1536)
    pub ddc_sample_rate_rx2: u16, // kHz
    pub diversity_autonull_result: u16, // 0=not done, >0 = improvement*10+32000
}

impl Default for RadioState {
    fn default() -> Self {
        Self {
            connected: false,
            ptt_denied: false,
            audio_error: false,
            rtt_ms: 0,
            jitter_ms: 0.0,
            buffer_depth: 0,
            rx_packets: 0,
            loss_percent: 0,
            capture_level: 0.0,
            playback_level: 0.0,
            playback_level_bin_r: 0.0,
            playback_level_rx2: 0.0,
            playback_level_yaesu: 0.0,
            yaesu_mic_level: 0.0,
            frequency_hz: 0,
            mode: 0,
            smeter: 0,
            power_on: false,
            tx_profile: 0,
            nr_level: 0,
            anf_on: false,
            drive_level: 0,
            rx_af_gain: 0,
            agc_enabled: false,
            other_tx: false,
            recording: false,
            playing: false,
            last_recorded_path: None,
            thetis_swr_x100: 100,
            filter_low_hz: 0,
            filter_high_hz: 0,
            thetis_starting: false,
            mon_on: false,
            tx_profile_names: Vec::new(),
            rx2_enabled: false,
            vfo_sync: false,
            frequency_rx2_hz: 0,
            mode_rx2: 0,
            smeter_rx2: 0,
            rx2_af_gain: 0,
            rx2_nr_level: 0,
            rx2_anf_on: false,
            rx2_agc_mode: 3,
            rx2_agc_gain: 80,
            rx2_sql_enable: false,
            rx2_sql_level: 0,
            rx2_nb_enable: false,
            rx2_binaural: false,
            rx2_apf_enable: false,
            rx2_vfo_lock: false,
            filter_rx2_low_hz: 0,
            filter_rx2_high_hz: 0,
            rx2_spectrum_bins: Vec::new(),
            rx2_spectrum_center_hz: 0,
            rx2_spectrum_span_hz: 0,
            rx2_spectrum_ref_level: 0,
            rx2_spectrum_db_per_unit: 1,
            rx2_spectrum_sequence: 0,
            rx2_full_spectrum_bins: Vec::new(),
            rx2_full_spectrum_center_hz: 0,
            rx2_full_spectrum_span_hz: 0,
            rx2_full_spectrum_sequence: 0,
            spectrum_bins: Vec::new(),
            spectrum_center_hz: 0,
            spectrum_span_hz: 0,
            spectrum_ref_level: 0,
            spectrum_db_per_unit: 1,
            spectrum_sequence: 0,
            full_spectrum_bins: Vec::new(),
            full_spectrum_center_hz: 0,
            full_spectrum_span_hz: 0,
            full_spectrum_sequence: 0,
            amplitec_connected: false,
            amplitec_switch_a: 0,
            amplitec_switch_b: 0,
            amplitec_labels: String::new(),
            tuner_connected: false,
            tuner_state: 0,
            tuner_can_tune: false,
            spe_connected: false,
            spe_state: 0,
            spe_band: 0,
            spe_ptt: false,
            spe_power_w: 0,
            spe_swr_x10: 10,
            spe_temp: 0,
            spe_warning: b'N',
            spe_alarm: b'N',
            spe_power_level: 0,
            spe_antenna: 0,
            spe_input: 0,
            spe_voltage_x10: 0,
            spe_current_x10: 0,
            spe_atu_bypassed: false,
            spe_available: false,
            spe_active: false,
            rf2k_connected: false,
            rf2k_operate: false,
            rf2k_band: 0,
            rf2k_frequency_khz: 0,
            rf2k_temperature_x10: 0,
            rf2k_voltage_x10: 0,
            rf2k_current_x10: 0,
            rf2k_forward_w: 0,
            rf2k_reflected_w: 0,
            rf2k_swr_x100: 100,
            rf2k_max_forward_w: 0,
            rf2k_max_reflected_w: 0,
            rf2k_max_swr_x100: 100,
            rf2k_error_state: 0,
            rf2k_error_text: String::new(),
            rf2k_antenna_type: 0,
            rf2k_antenna_number: 1,
            rf2k_tuner_mode: 0,
            rf2k_tuner_setup: String::new(),
            rf2k_tuner_l_nh: 0,
            rf2k_tuner_c_pf: 0,
            rf2k_tuner_freq_khz: 0,
            rf2k_segment_size_khz: 0,
            rf2k_drive_w: 0,
            rf2k_modulation: String::new(),
            rf2k_max_power_w: 0,
            rf2k_device_name: String::new(),
            rf2k_available: false,
            rf2k_active: false,
            rf2k_debug_available: false,
            rf2k_bias_pct_x10: 0,
            rf2k_psu_source: 0,
            rf2k_uptime_s: 0,
            rf2k_tx_time_s: 0,
            rf2k_error_count: 0,
            rf2k_error_history: Vec::new(),
            rf2k_storage_bank: 0,
            rf2k_hw_revision: String::new(),
            rf2k_frq_delay: 0,
            rf2k_autotune_threshold_x10: 0,
            rf2k_dac_alc: 0,
            rf2k_high_power: false,
            rf2k_tuner_6m: false,
            rf2k_band_gap_allowed: false,
            rf2k_controller_version: 0,
            rf2k_drive_config_ssb: [0; 11],
            rf2k_drive_config_am: [0; 11],
            rf2k_drive_config_cont: [0; 11],
            ub_connected: false,
            ub_frequency_khz: 0,
            ub_band: 0,
            ub_direction: 0,
            ub_off_state: true,
            ub_motors_moving: 0,
            ub_motor_completion: 0,
            ub_fw_major: 0,
            ub_fw_minor: 0,
            ub_available: false,
            ub_elements_mm: [0; 6],
            dx_spots: Vec::new(),
            rotor_connected: false,
            rotor_angle_x10: 0,
            rotor_rotating: false,
            rotor_target_x10: 0,
            rotor_available: false,
            yaesu_connected: false,
            yaesu_freq_a: 0,
            yaesu_freq_b: 0,
            yaesu_mode: 1,
            yaesu_smeter: 0,
            yaesu_tx_active: false,
            yaesu_power_on: false,
            yaesu_af_gain: 0,
            yaesu_tx_power: 0,
            yaesu_squelch: 0,
            yaesu_rf_gain: 0,
            yaesu_mic_gain: 0,
            yaesu_split: false,
            yaesu_scan: false,
            yaesu_vfo_select: 0,
            yaesu_memory_channel: 0,
            yaesu_memory_data: None,
            agc_mode: 3, // med
            agc_gain: 80,
            rit_enable: false,
            rit_offset: 0,
            xit_enable: false,
            xit_offset: 0,
            sql_enable: false,
            sql_level: 0,
            nb_enable: false,
            nb_level: 0,
            agc_auto_rx1: false,
            agc_auto_rx2: false,
            cw_keyer_speed: 20,
            vfo_lock: false,
            binaural: false,
            apf_enable: false,
            mute: false,
            rx_mute: false,
            nf_enable: false,
            rx2_nf_enable: false,
            rx_balance: 0,
            tune_drive: 0,
            mon_volume: -40,
            auth_rejected: false,
            totp_required: false,
            diversity_enabled: false,
            diversity_ref: 1,
            diversity_source: 0,
            diversity_gain_rx1: 1500,
            diversity_gain_rx2: 1500,
            diversity_phase: 18000,
            ddc_sample_rate_rx1: 0,
            ddc_sample_rate_rx2: 0,
            diversity_autonull_result: 0,
        }
    }
}
