// SPDX-License-Identifier: GPL-2.0-or-later

package com.sdrremote

data class DxSpotInfo(
    val callsign: String,
    val frequencyHz: Long,
    val mode: String,
    val spotter: String,
    val comment: String,
    val ageSeconds: Int,
    val expirySeconds: Int,
)

data class SdrUiState(
    val initError: String? = null,
    val connected: Boolean = false,
    // Fase 3c: relay audio on the wss TCP-fallback (true) vs low-latency UDP (false).
    val relayTransportFallback: Boolean = false,
    val pttDenied: Boolean = false,
    val audioError: Boolean = false,
    val authRejected: Boolean = false,
    val totpRequired: Boolean = false,
    // PATCH-1: pre-rendered connect-status text from Rust i18n.rs
    val connectStatusHeadline: String = "",
    val connectStatusAction: String = "",
    val connectStatusIsError: Boolean = false,
    val connectStatusIsAwaitingTotp: Boolean = false,
    val rttMs: Int = 0,
    val jitterMs: Float = 0f,
    val bufferDepth: Int = 0,
    val rxPackets: Long = 0,
    val yaesuAudioPackets: Long = 0,
    val yaesuJitterMs: Float = 0f,
    val yaesuBufferDepth: Int = 0,
    val yaesu2AudioPackets: Long = 0,
    val yaesu2JitterMs: Float = 0f,
    val yaesu2BufferDepth: Int = 0,
    val vrx1AudioPackets: Long = 0,
    val vrx1JitterMs: Float = 0f,
    val vrx1BufferDepth: Int = 0,
    val vrx2AudioPackets: Long = 0,
    val vrx2JitterMs: Float = 0f,
    val vrx2BufferDepth: Int = 0,
    val lossPercent: Int = 0,
    val downKbps: Int = 0,
    val upKbps: Int = 0,
    val dxSpotsEnabled: Boolean = true,
    val captureLevel: Float = 0f,
    /// TX level of the Yaesu chain. The Thetis capture level is a different
    /// meter and reads silence while a Yaesu is keyed.
    val yaesuMicLevel: Float = 0f,
    val playbackLevel: Float = 0f,
    val frequencyHz: Long = 0,
    val frequencyRx2Hz: Long = 0,
    val mode: Int = 0,
    val smeter: Float = -200f,
    val powerOn: Boolean = false,
    val txProfile: Int = 0,
    val nrLevel: Int = 0,
    val anfOn: Boolean = false,
    val nbLevel: Int = 0,
    val diversityEnabled: Boolean = false,
    val diversityPhase: Float = 0f,
    val diversityGainRx1: Float = 1f,
    val diversityGainRx2: Float = 1f,
    val diversityRef: Int = 0,
    val diversitySource: Int = 0,
    val diversityAutonullResult: Int = 0,
    val driveLevel: Int = 0,
    val rxAfGain: Int = 0,
    val agcEnabled: Boolean = false,
    val otherTx: Boolean = false,
    val transmitting: Boolean = false,
    val filterLowHz: Int = 0,
    val filterHighHz: Int = 0,
    val thetisConfigured: Boolean = true,
    val thetisStarting: Boolean = false,
    /// Server explicitly reports Thetis is not running on the server PC.
    /// Drives the Thetis-autostart option on the Radio screen.
    val thetisNotRunning: Boolean = false,
    val txProfileNames: List<String> = emptyList(),
    // Spectrum (extracted view)
    val spectrumBins: List<UByte> = emptyList(),
    val spectrumCenterHz: Long = 0,
    val spectrumSpanHz: Long = 0,
    val spectrumRefLevel: Int = 0,
    val spectrumDbPerUnit: Int = 1,
    val spectrumSequence: Int = 0,
    // Full DDC spectrum (for waterfall)
    val fullSpectrumBins: List<UByte> = emptyList(),
    val fullSpectrumCenterHz: Long = 0,
    val fullSpectrumSpanHz: Long = 0,
    val fullSpectrumSequence: Int = 0,
    // External equipment
    val amplitecConnected: Boolean = false,
    val amplitecSwitchA: Int = 0,
    val amplitecSwitchB: Int = 0,
    val amplitecLabels: String = "",
    // Tuner
    val tunerConnected: Boolean = false,
    val tunerState: Int = 0,
    val tunerCanTune: Boolean = false,
    // SPE Expert
    val speConnected: Boolean = false,
    val speState: Int = 0,
    val speBand: Int = 0,
    val spePtt: Boolean = false,
    val spePowerW: Int = 0,
    val speSwrX10: Int = 0,
    val speTemp: Int = 0,
    val speWarning: Int = 0,
    val speAlarm: Int = 0,
    val spePowerLevel: Int = 0,
    val speAntenna: Int = 0,
    val speInput: Int = 0,
    val speVoltageX10: Int = 0,
    val speCurrentX10: Int = 0,
    val speAtuBypassed: Boolean = false,
    val speAvailable: Boolean = false,
    val speActive: Boolean = false,
    // RF2K-S Amplifier
    val rf2kConnected: Boolean = false,
    val rf2kOperate: Boolean = false,
    val rf2kBand: Int = 0,
    val rf2kFrequencyKhz: Int = 0,
    val rf2kTemperatureX10: Int = 0,
    val rf2kVoltageX10: Int = 0,
    val rf2kCurrentX10: Int = 0,
    val rf2kForwardW: Int = 0,
    val rf2kReflectedW: Int = 0,
    val rf2kSwrX100: Int = 100,
    val rf2kMaxForwardW: Int = 0,
    val rf2kMaxReflectedW: Int = 0,
    val rf2kMaxSwrX100: Int = 100,
    val rf2kErrorState: Int = 0,
    val rf2kErrorText: String = "",
    val rf2kAntennaType: Int = 0,
    val rf2kAntennaNumber: Int = 1,
    val rf2kTunerMode: Int = 0,
    val rf2kTunerSetup: String = "",
    val rf2kTunerLNh: Int = 0,
    val rf2kTunerCPf: Int = 0,
    val rf2kDriveW: Int = 0,
    val rf2kModulation: String = "",
    val rf2kMaxPowerW: Int = 0,
    val rf2kDeviceName: String = "",
    val rf2kAvailable: Boolean = false,
    val rf2kActive: Boolean = false,
    // Yaesu FT-991A
    val yaesuConnected: Boolean = false,
    val yaesuFreqA: Long = 0,
    val yaesuFreqB: Long = 0,
    val yaesuMode: Int = 0,
    val yaesuSmeter: Int = 0,
    val yaesuTxActive: Boolean = false,
    val yaesuPowerOn: Boolean = false,
    val yaesuAfGain: Int = 0,
    val yaesuTxPower: Int = 0,
    val yaesuSquelch: Int = 0,
    val yaesuRfGain: Int = 0,
    val yaesuMicGain: Int = 0,
    val yaesuVfoSelect: Int = 0,
    val yaesuMemoryChannel: Int = 0,
    val yaesuSplit: Boolean = false,
    val yaesuScan: Boolean = false,
    val playbackLevelYaesu: Float = 0f,
    val yaesuMemoryData: String = "",
    /// EX/menu values, separate from the memory list. They used to share one
    /// field with a "MENU:" prefix to tell them apart; since the server pushes
    /// both on connect they arrive together and one hid the other.
    val yaesuMenuData: String = "",
    val yaesu2MenuData: String = "",
    val yaesuModel: Int = 0, // 0=991A, 1=FTX-1
    val yaesuTunerState: Int = 0, // interne ATU: 0=uit, 1=aan, 2=tunend
    val yaesuHiSwr: Boolean = false, // radio meldt hoge SWR tijdens TX (zelf-wissend)
    val yaesuTxPowerMax: Int = 0, // max TX-vermogen huidige band (EX max-power; 0=onbekend)
    // DSP/functie-feature-state radio 1 (typed control channel)
    val yaesuFeatureToggles: UInt = 0u,
    val yaesuFeatureLevels: List<Int> = emptyList(),
    val yaesuFeatureFreqs: List<Int> = emptyList(),
    // Radio 2 (yaesu2) — Android toont één radio tegelijk; selectedRadio kiest welke.
    val yaesu2Connected: Boolean = false,
    val yaesu2Model: Int = 1,
    val yaesu2TunerState: Int = 0,
    val yaesu2HiSwr: Boolean = false,
    val yaesu2FreqA: Long = 0,
    val yaesu2FreqB: Long = 0,
    val yaesu2Mode: Int = 0,
    val yaesu2Smeter: Int = 0,
    val yaesu2TxActive: Boolean = false,
    val yaesu2PowerOn: Boolean = false,
    val yaesu2AfGain: Int = 0,
    val yaesu2TxPower: Int = 0,
    val yaesu2TxPowerMax: Int = 0, // max TX-vermogen huidige band (EX max-power; 0=onbekend)
    val yaesu2Squelch: Int = 0,
    val yaesu2RfGain: Int = 0,
    val yaesu2MicGain: Int = 0,
    val yaesu2VfoSelect: Int = 0,
    val yaesu2MemoryChannel: Int = 0,
    val yaesu2Split: Boolean = false,
    val yaesu2Scan: Boolean = false,
    val playbackLevelYaesu2: Float = 0f,
    val yaesu2MemoryData: String = "",
    val yaesu2FeatureToggles: UInt = 0u,
    val yaesu2FeatureLevels: List<Int> = emptyList(),
    val yaesu2FeatureFreqs: List<Int> = emptyList(),
    /** Gekozen Yaesu-radio in de UI: 0=radio1, 1=radio2 (Android bedient er één tegelijk). */
    val selectedRadio: Int = 0,
    // UltraBeam RCU-06
    val ubConnected: Boolean = false,
    val ubFrequencyKhz: Int = 0,
    val ubBand: Int = 0,
    val ubDirection: Int = 0,
    val ubOffState: Boolean = true,
    val ubMotorsMoving: Int = 0,
    val ubMotorCompletion: Int = 0,
    val ubFwMajor: Int = 0,
    val ubFwMinor: Int = 0,
    val ubAvailable: Boolean = false,
    val ubElementsMm: List<Int> = listOf(0, 0, 0, 0, 0, 0),
    // Rotor
    val rotorConnected: Boolean = false,
    val rotorAngleX10: Int = 0,
    val rotorRotating: Boolean = false,
    val rotorTargetX10: Int = 0,
    val rotorAvailable: Boolean = false,
    // DX Cluster spots
    val dxSpots: List<DxSpotInfo> = emptyList(),
)
