package com.sdrremote

data class DxSpotInfo(
    val callsign: String,
    val frequencyHz: Long,
    val mode: String,
    val spotter: String,
    val comment: String,
    val ageSeconds: Int,
    val expirySeconds: Int,
)

data class SdrUiState(
    val initError: String? = null,
    val connected: Boolean = false,
    val pttDenied: Boolean = false,
    val audioError: Boolean = false,
    val authRejected: Boolean = false,
    val totpRequired: Boolean = false,
    val rttMs: Int = 0,
    val jitterMs: Float = 0f,
    val bufferDepth: Int = 0,
    val rxPackets: Long = 0,
    val lossPercent: Int = 0,
    val captureLevel: Float = 0f,
    val playbackLevel: Float = 0f,
    val frequencyHz: Long = 0,
    val frequencyRx2Hz: Long = 0,
    val mode: Int = 0,
    val smeter: Int = 0,
    val powerOn: Boolean = false,
    val txProfile: Int = 0,
    val nrLevel: Int = 0,
    val anfOn: Boolean = false,
    val nbLevel: Int = 0,
    val diversityEnabled: Boolean = false,
    val diversityPhase: Float = 0f,
    val diversityGainRx1: Float = 1f,
    val diversityGainRx2: Float = 1f,
    val diversityRef: Int = 0,
    val diversitySource: Int = 0,
    val diversityAutonullResult: Int = 0,
    val driveLevel: Int = 0,
    val rxAfGain: Int = 0,
    val agcEnabled: Boolean = false,
    val otherTx: Boolean = false,
    val transmitting: Boolean = false,
    val filterLowHz: Int = 0,
    val filterHighHz: Int = 0,
    val thetisStarting: Boolean = false,
    val txProfileNames: List<String> = emptyList(),
    // Spectrum (extracted view)
    val spectrumBins: List<UByte> = emptyList(),
    val spectrumCenterHz: Long = 0,
    val spectrumSpanHz: Long = 0,
    val spectrumRefLevel: Int = 0,
    val spectrumDbPerUnit: Int = 1,
    val spectrumSequence: Int = 0,
    // Full DDC spectrum (for waterfall)
    val fullSpectrumBins: List<UByte> = emptyList(),
    val fullSpectrumCenterHz: Long = 0,
    val fullSpectrumSpanHz: Long = 0,
    val fullSpectrumSequence: Int = 0,
    // External equipment
    val amplitecConnected: Boolean = false,
    val amplitecSwitchA: Int = 0,
    val amplitecSwitchB: Int = 0,
    val amplitecLabels: String = "",
    // Tuner
    val tunerConnected: Boolean = false,
    val tunerState: Int = 0,
    val tunerCanTune: Boolean = false,
    // SPE Expert
    val speConnected: Boolean = false,
    val speState: Int = 0,
    val speBand: Int = 0,
    val spePtt: Boolean = false,
    val spePowerW: Int = 0,
    val speSwrX10: Int = 0,
    val speTemp: Int = 0,
    val speWarning: Int = 0,
    val speAlarm: Int = 0,
    val spePowerLevel: Int = 0,
    val speAntenna: Int = 0,
    val speInput: Int = 0,
    val speVoltageX10: Int = 0,
    val speCurrentX10: Int = 0,
    val speAtuBypassed: Boolean = false,
    val speAvailable: Boolean = false,
    val speActive: Boolean = false,
    // RF2K-S Amplifier
    val rf2kConnected: Boolean = false,
    val rf2kOperate: Boolean = false,
    val rf2kBand: Int = 0,
    val rf2kFrequencyKhz: Int = 0,
    val rf2kTemperatureX10: Int = 0,
    val rf2kVoltageX10: Int = 0,
    val rf2kCurrentX10: Int = 0,
    val rf2kForwardW: Int = 0,
    val rf2kReflectedW: Int = 0,
    val rf2kSwrX100: Int = 100,
    val rf2kMaxForwardW: Int = 0,
    val rf2kMaxReflectedW: Int = 0,
    val rf2kMaxSwrX100: Int = 100,
    val rf2kErrorState: Int = 0,
    val rf2kErrorText: String = "",
    val rf2kAntennaType: Int = 0,
    val rf2kAntennaNumber: Int = 1,
    val rf2kTunerMode: Int = 0,
    val rf2kTunerSetup: String = "",
    val rf2kTunerLNh: Int = 0,
    val rf2kTunerCPf: Int = 0,
    val rf2kDriveW: Int = 0,
    val rf2kModulation: String = "",
    val rf2kMaxPowerW: Int = 0,
    val rf2kDeviceName: String = "",
    val rf2kAvailable: Boolean = false,
    val rf2kActive: Boolean = false,
    // Yaesu FT-991A
    val yaesuConnected: Boolean = false,
    val yaesuFreqA: Long = 0,
    val yaesuFreqB: Long = 0,
    val yaesuMode: Int = 0,
    val yaesuSmeter: Int = 0,
    val yaesuTxActive: Boolean = false,
    val yaesuPowerOn: Boolean = false,
    val yaesuAfGain: Int = 0,
    val yaesuTxPower: Int = 0,
    val yaesuSquelch: Int = 0,
    val yaesuRfGain: Int = 0,
    val yaesuMicGain: Int = 0,
    val yaesuVfoSelect: Int = 0,
    val yaesuMemoryChannel: Int = 0,
    val yaesuSplit: Boolean = false,
    val yaesuScan: Boolean = false,
    val playbackLevelYaesu: Float = 0f,
    val yaesuMemoryData: String = "",
    // UltraBeam RCU-06
    val ubConnected: Boolean = false,
    val ubFrequencyKhz: Int = 0,
    val ubBand: Int = 0,
    val ubDirection: Int = 0,
    val ubOffState: Boolean = true,
    val ubMotorsMoving: Int = 0,
    val ubMotorCompletion: Int = 0,
    val ubFwMajor: Int = 0,
    val ubFwMinor: Int = 0,
    val ubAvailable: Boolean = false,
    val ubElementsMm: List<Int> = listOf(0, 0, 0, 0, 0, 0),
    // Rotor
    val rotorConnected: Boolean = false,
    val rotorAngleX10: Int = 0,
    val rotorRotating: Boolean = false,
    val rotorTargetX10: Int = 0,
    val rotorAvailable: Boolean = false,
    // DX Cluster spots
    val dxSpots: List<DxSpotInfo> = emptyList(),
)
